重写模块 mcbbs_news
Teahouse-Studios/akari-bot pull request #287
Opened 2022-07-14 16:39 UTC by HornCopper

重写了模块`mcbbs_news`，使用了聊天记录转发、附带作者及发布时间。

2022-07-15 15:30 UTC, Dianliang233 commented
我不明白为什么要用聊天记录转发

2022-07-15 15:32 UTC, HornCopper commented
你有没有想过一页到底有多少，刷屏的情况无法避免，除非截取，然而截取势必会损失一部分信息，如此，用聊天记录既能不刷屏，又可以尽可能多地呈现信息

2022-07-15 16:13 UTC, Dianliang233 requested changes

2022-07-15 16:13 UTC, Dianliang233 commented on modules/mcbbs_news/mcbbs_news.py
> +        x = BeautifulSoup(str(i), "html.parser")
为什么要先转成string，又转回来。。。

2022-07-15 16:13 UTC, Dianliang233 commented on modules/mcbbs_news/mcbbs_news.py
> +    links = []
这样写不如原来一个dictionary的list。。不是很优雅

2022-07-15 16:13 UTC, Dianliang233 commented on modules/mcbbs_news/__init__.py
> -    desc='获得 MCBBS 幻翼快讯版最新新闻（未被版主高亮过的新闻将被忽略）',
没有被高亮的新闻应该被忽略，因为没有版主查看过，有可能是水贴。

2022-07-15 16:13 UTC, Dianliang233 commented on modules/mcbbs_news/__init__.py
> +            for i in range(len(titles)):
不需要每一条都发。快速获取新闻，不需要一个月之前的东西

2022-07-15 16:14 UTC, HornCopper commented on modules/mcbbs_news/mcbbs_news.py
> +        x = BeautifulSoup(str(i), "html.parser")
那您试试会不会有NoneType

2022-07-15 16:16 UTC, HornCopper commented on modules/mcbbs_news/__init__.py
> -    desc='获得 MCBBS 幻翼快讯版最新新闻（未被版主高亮过的新闻将被忽略）',
有可能，那如果是有意义的呢.jpg 聊天记录这个地方无论是不是水贴都会弄进来，不必担心数据多少问题

2022-07-15 16:16 UTC, HornCopper commented on modules/mcbbs_news/__init__.py
> +            for i in range(len(titles)):
火星人还是有的啊，你能保证要查的人一定看过了一个月前的东西？而且这边只是截取了第一页所呈现的信息，大多数情况下，它们都不应该过于过时。

2022-07-15 16:17 UTC, HornCopper commented
No.3 认可 其余有待商榷

2022-07-15 16:21 UTC, Dianliang233 commented on modules/mcbbs_news/__init__.py
> +            for i in range(len(titles)):
火星人应该直接去看论坛，这个目标是需要快速获取并分享mcbbs最新翻译新闻的人

2022-07-15 16:22 UTC, Dianliang233 commented on modules/mcbbs_news/__init__.py
> -    desc='获得 MCBBS 幻翼快讯版最新新闻（未被版主高亮过的新闻将被忽略）',
版主通常会在很快的时间内就处理。你不混新闻版你不知道。

2022-07-15 16:22 UTC, HornCopper commented on modules/mcbbs_news/__init__.py
> +            for i in range(len(titles)):
我认为阁下的目标有些片面，快速获取信息的用户，或许并不想打开浏览器在打开mcbbs（在他们知道有功能可以查的时候）

2022-07-15 16:23 UTC, HornCopper commented on modules/mcbbs_news/__init__.py
> -    desc='获得 MCBBS 幻翼快讯版最新新闻（未被版主高亮过的新闻将被忽略）',
照你这么说，看新闻的都是混新闻版的了

2022-07-15 16:24 UTC, HornCopper commented on modules/mcbbs_news/__init__.py
> -    desc='获得 MCBBS 幻翼快讯版最新新闻（未被版主高亮过的新闻将被忽略）',
况且，我并不反对阁下您对代码做出更改，您可以提交您的修改并分享您的意见。

2022-07-16 03:33 UTC, Dianliang233 commented
author, date, category 已于 691de90 实现

其他暂不考虑

2022-07-16 03:33 UTC, closed without merging