feat: support modrinth and original API
Teahouse-Studios/akari-bot pull request #535
Opened 2023-04-08 16:51 UTC by z0z0r4

支持 modrinth 以及使用官方 curseforge API

2023-04-08 16:51 UTC, z0z0r4 commented
https://github.com/Teahouse-Studios/akari-bot/issues/526

2023-04-08 17:06 UTC, HornCopper commented
你上传的东西自己没测试过吗（
你的CurseForge API链接访问过去就是403，我这边香港和内地的IP都试过了

2023-04-09 02:55 UTC, z0z0r4 commented
Authentication C Eternal API (curseforge.com)<https://docs.curseforge.com/#authentication>
________________________________
发件人: HornCopper ***@***.***>
发送时间: 2023年4月9日 1:07
收件人: Teahouse-Studios/akari-bot ***@***.***>
抄送: z0z0r4 ***@***.***>; Author ***@***.***>
主题: Re: [Teahouse-Studios/akari-bot] feat: support modrinth and original API (PR #535)


你上传的东西自己没测试过吗（
你的CurseForge API链接访问过去就是403，我这边香港和内地的IP都试过了

―
Reply to this email directly, view it on GitHub<https://github.com/Teahouse-Studios/akari-bot/pull/535#issuecomment-1500935414>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ASYYUOKGPMOMHAG2QPWNPVDXAGLLPANCNFSM6AAAAAAWXRZS2U>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-04-09 04:00 UTC, Dianliang233 requested changes

2023-04-09 04:00 UTC, Dianliang233 commented on modules/mod_dl/__init__.py
> +    developers=['HornCopper', 'OasisAkari', 'z0z0r4'],
typo

2023-04-09 04:00 UTC, Dianliang233 commented on modules/mod_dl/__init__.py
> +                    await msg.finish("未找到指定版本。")
newline plz

2023-04-09 04:38 UTC, z0z0r4 commented on modules/mod_dl/__init__.py
> +    developers=['HornCopper', 'OasisAkari', 'z0z0r4'],
sorrrrry

2023-04-09 04:39 UTC, z0z0r4 commented
fixed https://github.com/Teahouse-Studios/akari-bot/pull/535/commits/56fda00e4ee04a238aea60e0d17a04ab9b5ef2ad

2023-04-12 04:28 UTC, merged