[New]: 增添新模块【Hitokoto】和【You are the best】
Teahouse-Studios/akari-bot pull request #548
Opened 2023-04-16 02:13 UTC by SilianZ

详细改动请看Commits
这是 #491 的后继Pull Request

2023-04-16 04:44 UTC, Dianliang233 requested changes

2023-04-16 04:44 UTC, Dianliang233 commented on modules/hitokoto/get.py
> +    responce = requests.get(url)
用 get_url，不要用 requests

2023-04-16 04:44 UTC, Dianliang233 commented on modules/hitokoto/get.py
> +    get_json = responce.json()
这个命名听起来像函数，不要用

2023-04-16 04:44 UTC, Dianliang233 commented on modules/hitokoto/get.py
> +        send_msg = '一言 #' + str(get_json['id']) + '\n\n' + get_json['hitokoto'] + '\n\n来源：' + type_to_name[get_json['type']] + '——' + get_json['from'] + ' ' + get_json['from_who']
i18n

2023-04-16 04:44 UTC, Dianliang233 commented
以及我不太喜欢那个彩虹屁。

2023-04-16 05:54 UTC, z0z0r4 commented
> 以及我不太喜欢那个彩虹屁。

老实说好抽象（

2023-04-16 13:57 UTC, SilianZ commented
已根据要求修改了【Hitokoto】模块的代码

2023-05-04 10:09 UTC, DoroWolf commented
考虑认为彩虹屁模块可能不会采用

2023-05-04 10:09 UTC, DoroWolf commented
考虑彩虹屁模块不太合适

2023-05-04 10:11 UTC, DoroWolf commented
这个PR我稍候会合并，但是我会把不合适的部分改掉

2023-05-04 11:00 UTC, merged