增加【Music】模块
Teahouse-Studios/akari-bot pull request #583
Opened 2023-04-30 17:20 UTC by SilianZ

增加【Music】模块，目前可以进行搜索歌曲并获取指定歌曲信息。

具体改动请查看Commits

2023-05-02 16:53 UTC, DoroWolf commented
字符串命名有点脑梗(雾

2023-05-02 17:40 UTC, DoroWolf requested changes

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/locales/zh_tw.json
> +}
无需加入`zh_cn`以外的文件，机器人会处理好这个的;)

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/locales/en_us.json
> +}
无需加入`zh_cn`以外的文件，机器人会处理好这个的;)

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/locales/zh_cn.json
> +    "ncmusic.info.song_url":"歌曲链接："
为了便于机器人维护，所有字符串请以“模块名称.help/message.用途”的格式命名。

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/__init__.py
> +                            available_for = '*', support_languages=['zh_cn', 'zh_tw', 'en_us'])
```suggestion
```
如无必要，勿增实体。

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/__init__.py
> +                send_msg += msg.locale.t('ncmusic.character.)')
此处是否可以通过变量的方式解决？
示例：
`（bar） -> msg.locale.t('test', foo=bar)`

`"test": ""（${foo}）"`

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/__init__.py
> +                send_msg += msg.locale.t('ncmusic.character.)')
问题同上

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/__init__.py
> +            send_msg += msg.locale.t('ncmusic.character.(') + str(k['id']) + msg.locale.t('ncmusic.character.)')
```suggestion
            send_msg += msg.locale.t('ncmusic.message.character', character=str(k['id']))

```
这里可以用变量解决。

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/__init__.py
> +        await msg.finish()
```suggestion

```
机器人自带技术性错误的提示。

2023-05-02 17:40 UTC, DoroWolf commented on modules/netease_cloud_music/__init__.py
> +        await msg.finish()
```suggestion
    
```
问题同上。

2023-05-06 15:24 UTC, SilianZ commented
行全给你整好了，代码还是有点屎山

2023-05-28 13:19 UTC, DoroWolf approved these changes

2023-05-28 13:19 UTC, merged

2023-05-28 13:33 UTC, DoroWolf commented
程序写的不错，下次别写了